SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_OUTS as AO JOIN ANIMAL_INS as AI ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE (AI.SEX_UPON_INTAKE NOT LIKE "%Neutered%" AND AI.SEX_UPON_INTAKE NOT LIKE "%Spayed%")
    AND (AO.SEX_UPON_OUTCOME LIKE "%Neutered%" OR AO.SEX_UPON_OUTCOME LIKE "%Spayed%")
ORDER BY AI.ANIMAL_ID